---
version: '3.3'
services:
    nginx:
      container_name: nginx
      image: nginx:latest
      volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      ports:
      - target: 80
        published: 80
        protocol: tcp
      depends_on:
        - mongo
        - static_website
        - db_connector
        - notification_server
        - text_gen
        - num_gen
        - prize_gen
        - server
    server:
      image: localhost:5000/mcquiggan/lafb-server:latest
      build:
        context: ./server
        dockerfile: Dockerfile
      ports:
      - "8084:8084"
    static_website:
      image: localhost:5000/mcquiggan/lafb-website:latest
      build:
        context: ./static_website
        dockerfile: Dockerfile
      ports:
      - "8089:8089"
    notification_server:
      image: localhost:5000/mcquiggan/lafb-notification_server:latest
      build:
        context: ./notification_server
        dockerfile: Dockerfile
      ports:
      - "9000:9000"
    db_connector:
      image: localhost:5000/mcquiggan/lafb-db_connector:latest
      build:
        context: ./db_connector
        dockerfile: Dockerfile
      ports:
      - "5001:5001"
    text_gen:
      image: localhost:5000/mcquiggan/lafb-text_gen:latest
      build:
        context: ./text-generator-lower
        dockerfile: Dockerfile
      ports:
      - "50001:50001"
    num_gen:
      image: localhost:5000/mcquiggan/lafb-num_gen:latest
      build:
        context: ./num-generator-long
        dockerfile: Dockerfile
      ports:
      - "50002:50002"
    prize_gen:
      image: localhost:5000/mcquiggan/lafb-prize_gen:latest
      build:
        context: ./prize-generator-big
        dockerfile: Dockerfile
      ports:
      - "50003:50003"
    mongo:
      image: mongo
      ports:
      - "27017:27017"
    mongo-seed:
      image: fvilers/mongo-seed:1.0.0
      environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      volumes:
      - ./data:/data
      command:
      - "mongoimport --host mongo --port 27017 --db test --mode upsert --type json --file /data/account.json --jsonArray"
      restart: on-failure
  
...

