---
version: '3.3'
services:
    nginx:
      container_name: nginx
      image: nginx:latest
      volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      ports:
      - target: 80
        published: 80
        protocol: tcp
      depends_on:
        - mongo
        - static_website
        - db_connector
        - notification_server
        - text_gen
        - num_gen
        - prize_gen
        - server
    server:
      image: localhost:5000/mcquiggan/lafb-server:latest
      build:
        context: ./server
        dockerfile: Dockerfile
      ports:
      - "8084:8084"
      depends_on:
        - mongo
    static_website:
      image: localhost:5000/mcquiggan/lafb-website:latest
      build:
        context: ./static_website
        dockerfile: Dockerfile
      ports:
      - "8089:8089"
      depends_on:
        - mongo
    notification_server:
      image: localhost:5000/mcquiggan/lafb-notification_server:latest
      build:
        context: ./notification_server
        dockerfile: Dockerfile
      ports:
      - "9000:9000"
      depends_on:
        - mongo
    db_connector:
      image: localhost:5000/mcquiggan/lafb-db_connector:latest
      build:
        context: ./db_connector
        dockerfile: Dockerfile
      ports:
      - "5001:5001"
      links:
        - mongo
      depends_on:
        - mongo
    text_gen:
      image: localhost:5000/mcquiggan/lafb-text_gen:latest
      build:
        context: ./text-generator-lower
        dockerfile: Dockerfile
      ports:
      - "50001:50001"
      depends_on:
        - mongo
    num_gen:
      image: localhost:5000/mcquiggan/lafb-num_gen:latest
      build:
        context: ./num-generator-long
        dockerfile: Dockerfile
      ports:
      - "50002:50002"
      depends_on:
        - mongo
    prize_gen:
      image: localhost:5000/mcquiggan/lafb-prize_gen:latest
      build:
        context: ./prize-gen-big-node
        dockerfile: Dockerfile
      ports:
      - "50003:50003"
      depends_on:
        - mongo
    mongo:
      image: mongo
      ports:
      - "27017:27017"
  
...

