version: '3.7'
services:
    nginx:
      image: nginx
      depends_on: 
      - client
      - server
      volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
      ports:
      - target: 80
        protocol: tcp
        published: 80
      container_name: nginx

    server:
      image: keepkarm/server:latest
      build:
        context: ./server
        dockerfile: Dockerfile
      ports:
      - "8084:8084"
    
    client:
      image: keepkarm/client:latest
      build:
        context: ./static_website
        dockerfile: Dockerfile
      ports:
      - "8089:8089"

    notificationserver:
      image: keepkarm/notify:latest
      build:
        context: ./notification_server
        dockerfile: Dockerfile
      ports:
      - "9000:9000"

    text_gen:
      image: keepkarm/text_gen:v1
      build:
        context: ./text_gen
        dockerfile: Dockerfile
      ports:
      - "9017:9017"

    num_gen:
      image: keepkarm/num_gen:v1
      build:
        context: ./num_gen
        dockerfile: Dockerfile
      ports:
      - "9018:9018"

    account:
      image: keepkarm/account:v1
      build:
        context: ./account
        dockerfile: Dockerfile
      ports:
      - "5002:5002"

    db_connector:
      image: keepkarm/db_connector:latest
      ports:
      - target: 5001
        published: 5001
        protocol: tcp
      depends_on:
        - mongo

    mongo:
      image: mongo
      ports:
      - "27017:27017"
