
version: '3.3'
services:
    nginx:
      image: nginx
      depends_on: 
      - client
      - server
      volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
      ports:
      - target: 80
        protocol: tcp
        published: 80

    server:
      image: keepkarm/server:latest
      build:
        context: ./server
        dockerfile: Dockerfile
      ports:
      - "8084:8084"
      depends_on:
      - account
    
    client:
      image: keepkarm/client:latest
      build:
        context: ./static_website
        dockerfile: Dockerfile
      ports:
      - "8089:8089"

    notificationserver:
      image: keepkarm/notify:latest
      build:
        context: ./notification_server
        dockerfile: Dockerfile
      ports:
      - "9000:9000"
      depends_on:
      - account

    text_gen:
      image: keepkarm/text_gen:v1
      build:
        args:
            FILE_VERSION: 1
        context: ./text_gen
        dockerfile: Dockerfile
      ports:
      - "9017:9017"
      depends_on:
      - server

    num_gen:
      image: keepkarm/num_gen:v2
      build:
        args:
            FILE_VERSION: 2
        context: ./num_gen
        dockerfile: Dockerfile
      ports:
      - "9018:9018"
      depends_on:
      - server

    account:
      image: keepkarm/account:v1
      build:
        args:
            FILE_VERSION: 1
        context: ./account
        dockerfile: Dockerfile
      ports:
      - "5002:5002"
      depends_on:
      - db_connector

    db_connector:
      image: keepkarm/db_connect:latest
      build:
        context: ./db_connector
        dockerfile: Dockerfile
      ports:
      - "5001:5001"
      depends_on:
      - mongo

    mongo:
      image: mongo
      ports:
      - "27017:27017"

