apiVersion: v1
kind: Pod
metadata:
  name: dbconnector
  labels:
    app: db_connector
spec:
  containers:
    - name: db_connector
      image: teamdeadweight/db_connector:latest
      ports:
      - containerPort: 5001
