apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-server
  labels: 
    app: notification_server
spec:
  selector:
    matchLabels:
      app: notification_server
  template:
    metadata:
      labels:
        app: notification_server
    spec:
      containers:
      - name: notification-server
        image: teamdeadweight/notification_server:latest
        ports:
        - containerPort: 9000
